artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_file: https://github.com/Gakshith/CSC317/raw/refs/heads/main/youtube_dataset.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion